### ISSUE TITLE
Bitcoin Stamps Balance API Enhancement for UTXO Bound Editions

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#435]
# Bitcoin Stamps Balance API Enhancement

### Bitcoin Stamps Balance API
```bash
curl -X GET 'https://dev.bitcoinstamps.xyz/api/v2/stamps/balance/bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej' | jq . | grep 00031 -B3 -A9
```

Current response:
```json
{
  "stamp": 200004,
  "tx_hash": "79c783edddef1c34b05689d8a79548ff4b92424b912d9fae373b48f259e466e1",
  "cpid": "A241301191507000031",
  "stamp_url": "https://stampchain.io/stamps/79c783edddef1c34b05689d8a79548ff4b92424b912d9fae373b48f259e466e1.png",
  "stamp_mimetype": "image/png",
  "divisible": 0,
  "supply": 300,
  "locked": 0,
  "creator": "bc1qnwl8sf76djmcccujdv46mx3nnrsysazs3a3spe",
  "creator_name": null,
  "balance": 5
}
```

### Counterparty API
```bash
curl -X GET 'https://api.counterparty.io:4000/v2/addresses/bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej/balances' | jq . | grep 0031 -A4 -B2
```

Current response:
```json
[
    {
      "address": null,
      "asset": "A241301191507000031",
      "quantity": 1,
      "utxo": "289121b53e1ccd5e6611debfecca1c15263ab754ab0e0e05941a17b5e3b665b4:2",
      "utxo_address": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej"
    },
    {
      "address": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej",
      "asset": "A241301191507000031",
      "quantity": 4,
      "utxo": null,
      "utxo_address": null
    }
]
```

## Proposed Enhanced Response
The enhanced endpoint will maintain the same URL structure but return additional UTXO information:

```bash
curl -X GET 'https://dev.bitcoinstamps.xyz/api/v2/stamps/balance/bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej'
```

Proposed response:
```json
{
  "stamp": 200004,
  "tx_hash": "79c783edddef1c34b05689d8a79548ff4b92424b912d9fae373b48f259e466e1",
  "cpid": "A241301191507000031",
  "stamp_url": "https://stampchain.io/stamps/79c783edddef1c34b05689d8a79548ff4b92424b912d9fae373b48f259e466e1.png",
  "stamp_mimetype": "image/png",
  "divisible": 0,
  "supply": 300,
  "locked": 0,
  "creator": "bc1qnwl8sf76djmcccujdv46mx3nnrsysazs3a3spe",
  "creator_name": null,
  "balance": 5,
  "address": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej",
  "cpid": "A241301191507000031",
  "unbound_quantity": 2,
  "utxos": [
    {
      "quantity": 1,
      "utxo": "10f8e495a5088dd90a731f4b2657bfb4e94b1f59d3961cbc960900d4e5ba44e5:0"
    },
    {
      "quantity": 2,
      "utxo": "10f8e495a545548dd90a731f4b2657bfb4e94b1f59d3961cbc960900d4e5ba44e5:0"
    }
  ]
}
```

## Key Changes

1. **Structure Preservation**
   - All existing top-level fields remain unchanged
   - Total balance continues to be shown in the `balance` field

2. **New Fields**
   - `address`: Query parameter address (for validation)
   - `cpid`: Counterparty asset ID (matches asset)
   - `unbound_quantity`: Tokens not tied to UTXOs
   - `utxos`: Array of UTXO-specific balances
     - `quantity`: Amount in specific UTXO
     - `utxo`: UTXO reference (txid:vout)

# Bitcoin Stamps Balance API Enhancement

[Previous sections with curl examples and responses remain the same until Implementation Considerations]

## Implementation Considerations

1. **Data Transformation**
   - Aggregate Counterparty API responses
   - Split between UTXO-bound and unbound quantities
   - Maintain existing stamp metadata
   - Process UTXO data for marketplace compatibility

2. **Performance & Caching**

   a. **Existing Redis Implementation**
   - Leverage current Redis infrastructure
   - Optimize cache keys for new UTXO data structure
   - Current implementation provides foundation for:
     - Balance caching
     - Stamp metadata caching
     - API response caching

   b. **Enhanced Caching Strategy**
   - Implement tiered caching timeframes:
     - UTXO status: 30-60 seconds
     - Balance aggregations: 2-5 minutes
     - Stamp metadata: 15-30 minutes
   - Cache invalidation triggers:
     - New block notifications
     - Direct UTXO updates
     - Balance changes

   c. **Query Optimization**
   - Batch Counterparty API queries
   - Optimize existing database queries for UTXO data
   - Index frequently queried UTXO fields

   d. **API Flexibility**
   - Add verbose flag support with default to true a non-verbose query would need to require cpid value. This can be implemented at a later stage:
     ```bash
     # Full UTXO details
     /api/v2/stamps/balance/{address}?verbose=true
     
     # Basic balance only
     /api/v2/stamps/balance/{address}?verbose=false
     ```
   - Direct CPID balance queries:
     ```bash
     # Quick balance lookup
     /api/v2/stamps/balance/{address}/{cpid}
     ```

   e. **Pagination Support**
   - Implement for large UTXO sets
   - Default limit: 50 UTXOs per request
   - Cursor-based pagination for efficiency

3. **Error Handling**
   - Handle missing/invalid UTXO data
   - Clear error messages
   - Maintain partial responses
   - Cache failure fallbacks

## Technical Implementation Path

1. Update `xcpService.ts`:
   - utilize Redis caching for UTXO data
   - Transform Counterparty API responses
   - Implement UTXO aggregation logic

2. API Layer Updates:
   - Add verbose flag handling
   - Implement pagination
   - Maintain backward compatibility

## Related Files
- Primary: `server/services/xcpService.ts`
- Cache: `server/services/cacheService.ts`
- Function: `getAddressBalances()` (line ~616)

## Next Steps
1. Update TypeScript interfaces
2. Implement transformation logic
3. Add test case examples and response structure in 'schema.yml'
4. Update documentation
5. Stage for testing

## Notes
- Existing clients remain compatible
- New fields provide UTXO-level granularity 
- Consider versioning the api
- Redis implementation provides robust caching foundation
- Balance between cache freshness and API performance

Reference: https://github.com/stampchain-io/BTCStampsExplorer/issues/449

  via: https://github.com/stampchain-io/BTCStampsExplorer/blob/dev/server/services/xcpService.ts#L616

**Comment by reinamora137** [comment]
```
and there is empty utxos data like this 
  {
        "stamp": 197070,
        "tx_hash": "4d89635c2e3baa64ebacffccc9df4197573862f1fa5a25bdd3adaf8780a2100c",
        "cpid": "A1420148703590218528",
        "stamp_url": "https://stampchain.io/stamps/4d89635c2e3baa64ebacffccc9df4197573862f1fa5a25bdd3adaf8780a2100c.gif",
        "stamp_mimetype": "image/gif",
        "divisible": 0,
        "supply": 100,
        "locked": 1,
        "creator": "bc1qkm055r7c0afvnyvw0ve49mgus4p3wna6zadwhy",
        "creator_name": null,
        "balance": 1,
        "utxos": [{ "quantity": 1, "utxo_address": "" }]
      }
```

**Comment by itttm127** [comment]
{
            "stamp": 200004,
            "tx_hash": "79c783edddef1c34b05689d8a79548ff4b92424b912d9fae373b48f259e466e1",
            "cpid": "A241301191507000031",
            "stamp_url": "https://stampchain.io/stamps/79c783edddef1c34b05689d8a79548ff4b92424b912d9fae373b48f259e466e1.png",
            "stamp_mimetype": "image/png",
            "divisible": 0,
            "supply": 300,
            "locked": 0,
            "creator": "bc1qnwl8sf76djmcccujdv46mx3nnrsysazs3a3spe",
            "creator_name": null,
            "unbound_quantity": 0,
            "address": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej",
            "balance": 5,
            "utxos":
              [
                {
                  "quantity": 5,
                  "utxo_address": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej",
                },
              ],
          },
          {
            "stamp": 197070,
            "tx_hash": "4d89635c2e3baa64ebacffccc9df4197573862f1fa5a25bdd3adaf8780a2100c",
            "cpid": "A1420148703590218528",
            "stamp_url": "https://stampchain.io/stamps/4d89635c2e3baa64ebacffccc9df4197573862f1fa5a25bdd3adaf8780a2100c.gif",
            "stamp_mimetype": "image/gif",
            "divisible": 0,
            "supply": 100,
            "locked": 1,
            "creator": "bc1qkm055r7c0afvnyvw0ve49mgus4p3wna6zadwhy",
            "creator_name": null,
            "unbound_quantity": 1,
            "address": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej",
            "balance": 1,
            "utxos": [],
          },
          
          I updated the data structure like this format.

**Comment by itttm127** [comment]
```
[
  {
    "stamp": 200004,
    "tx_hash": "79c783edddef1c34b05689d8a79548ff4b92424b912d9fae373b48f259e466e1",
    "cpid": "A241301191507000031",
    "stamp_url": "https://stampchain.io/stamps/79c783edddef1c34b05689d8a79548ff4b92424b912d9fae373b48f259e466e1.png",
    "stamp_mimetype": "image/png",
    "divisible": 0,
    "supply": 300,
    "locked": 0,
    "creator": "bc1qnwl8sf76djmcccujdv46mx3nnrsysazs3a3spe",
    "creator_name": null,
    "unbound_quantity": 0,
    "address": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej",
    "balance": 5,
    "utxos": [
      {
        "quantity": 5,
        "utxo_address": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej"
      }
    ]
  },
  {
    "stamp": 197070,
    "tx_hash": "4d89635c2e3baa64ebacffccc9df4197573862f1fa5a25bdd3adaf8780a2100c",
    "cpid": "A1420148703590218528",
    "stamp_url": "https://stampchain.io/stamps/4d89635c2e3baa64ebacffccc9df4197573862f1fa5a25bdd3adaf8780a2100c.gif",
    "stamp_mimetype": "image/gif",
    "divisible": 0,
    "supply": 100,
    "locked": 1,
    "creator": "bc1qkm055r7c0afvnyvw0ve49mgus4p3wna6zadwhy",
    "creator_name": null,
    "unbound_quantity": 1,
    "address": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej",
    "balance": 1,
    "utxos": []
  }
]
```
I updated the data structure like this

**Comment by reinamora137** [comment]
no update to schema.yml in the prior update

**Comment by itttm127** [comment]
```
    StampBalance:
      type: object
      properties:
        stamp:
          type: number
        tx_hash:
          type: string
        stamp_url:
          type: string
        stamp_mimetype:
          type: string
        divisible:
          type: number
        supply:
          type: number
          nullable: true
        locked:
          oneOf:
            - type: number
              nullable: true
            - type: boolean
              nullable: true
        creator:
          type: string
        creator_name:
          type: string
          nullable: true
        balance:
          oneOf:
            - type: number
              nullable: true
            - type: string
              nullable: true
          description: sum of unbound_quantity + quantity in each utxo component
        address:
          type: string
        cpid:
          type: string
        unbounded_quantity:
          type: number
        utxos:
          type: array
          items:
            type: object
            properties:
              utxo:
                type: string
              quantity:
                type: number
```
I added this structure into StampBalance on scheme
could you please explain to me what's wrong here ?
