### ISSUE TITLE
Add btcbalace to /balane endpoint 

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#505]
At the request of superex need to read this 

/api/v2/balance 

![image](https://github.com/user-attachments/assets/c0df884a-cfe2-4f08-b3a3-abe0e3e9a74f)

the output and schema.yml should look like the following

```
    BtcInfo:
      type: object
      properties:
        address:
          type: string
        balance:
          type: number
        txCount:
          type: number
        unconfirmedBalance:
          type: number
        unconfirmedTxCount:
          type: number
```

it will use the getBTCBalanceInfo method in lib/utils/balanceUtils.ts
